user_management/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns=[
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('product/', views.product_form, name='add_product'),
    path('seller/', views.seller_form, name='add_seller'),
    path('customer/', views.customer_form, name='add_customer'),
    path('sales/', views.sales_form, name='add_sales'),
    path('purchase/', views.purchase_form, name='add_purchase'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('product_data/', views.product_data, name='product_data'),
    path('seller_data/', views.seller_data, name='seller_data'),
    path('customer_data/', views.customer_data, name='customer_data'),
    path('sales_data/', views.sales_data, name='sales_data'),
    path('purchase_data/', views.purchase_data, name='purchase_data'),

]

user_management/user_management/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

user_management/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):


    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #Additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)


    def __str__(self):
        return self.user.username


############################Dashboard#####################################

class Product(models.Model):
    product_id = models.CharField(max_length=256,unique=True)
    product_type = models.CharField(max_length=256)
    product_name = models.CharField(max_length=256)
    product_rate = models.CharField(max_length=256)

    objects = models.Manager()


    def __str__(self):
        return self.product_id


class Seller(models.Model):
    seller_id = models.CharField(max_length=256,unique=True)
    seller_name = models.CharField(max_length=256)
    seller_number = models.CharField(max_length=256)
    seller_address = models.CharField(max_length=256)


    def __str__(self):
        return self.seller_id


class Customer(models.Model):
    customer_id = models.CharField(max_length=256,unique=True)
    customer_name = models.CharField(max_length=256)
    customer_number = models.CharField(max_length=256)
    customer_address = models.CharField(max_length=256)


    def __str__(self):
        return self.customer_id





class Sales(models.Model):
    seller_id = models.ForeignKey(Seller,related_name='seller_sales',on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product,related_name='product_sales',on_delete=models.CASCADE)
    sales_date = models.DateField()
    sales_qty = models.CharField(max_length=256)
    def __str__(self):
        return self.sales_qty


class Purchase(models.Model):
    customer_id = models.ForeignKey(Customer,related_name='customer_sales',on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product,related_name='customer_sales',on_delete=models.CASCADE)
    purchase_date = models.DateField()
    purchase_qty = models.CharField(max_length=256)
    def __str__(self):
        return self.purchase_qty

user_management/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo, Product, Seller, Customer, Sales, Purchase

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

#########################Dashboard###################################
class ProductForm(forms.ModelForm):
    class Meta():
        model = Product
        fields = ('product_id', 'product_type', 'product_name','product_rate')

class SellerForm(forms.ModelForm):
    class Meta():
        model = Seller
        fields = ('seller_id', 'seller_name', 'seller_number', 'seller_address')

class CustomerForm(forms.ModelForm):
    class Meta():
        model = Customer
        fields = ('customer_id', 'customer_name', 'customer_number', 'customer_address')

class SalesForm(forms.ModelForm):
    class Meta():
        model = Sales
        fields = ('seller_id', 'product_id', 'sales_date', 'sales_qty')


class PurchaseForm(forms.ModelForm):
    class Meta():
        model = Purchase
        fields = ('customer_id', 'product_id', 'purchase_date', 'purchase_qty')

user_management/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm, ProductForm, SellerForm, CustomerForm, SalesForm, PurchaseForm
from basic_app.models import Product, Seller, Customer ,Sales, Purchase
# Create your views here.

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required







def index(request):
    return render(request, 'basic_app/index.html')

def dashboard(request):
    return render(request, 'basic_app/dashboard.html')

def product_data(request):
    product_list = Product.objects.order_by('product_id')
    product_dict = {'product_data':product_list}
    return render(request, 'basic_app/product_data.html',context=product_dict)

def seller_data(request):
    seller_list = Seller.objects.order_by('seller_id')
    seller_dict = {'seller_data':seller_list}
    return render(request, 'basic_app/seller_data.html',context=seller_dict)

def customer_data(request):
    customer_list = Customer.objects.order_by('customer_id')
    customer_dict = {'customer_data':customer_list}
    return render(request, 'basic_app/customer_data.html',context=customer_dict)

def sales_data(request):
    sales_list = Sales.objects.order_by('-sales_date')
    sales_dict = {'sales_data':sales_list}
    return render(request, 'basic_app/sales_data.html',context=sales_dict)

def purchase_data(request):
    purchase_list = Purchase.objects.order_by('-purchase_date')
    purchase_dict = {'purchase_data':purchase_list}
    return render(request, 'basic_app/purchase_data.html',context=purchase_dict)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registraction.html',
                            {'user_form': user_form,
                              'profile_form':profile_form,
                              'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password {}".format(username,password))
            return render(request, 'basic_app/loginfail.html',{})
    else:
        return render(request, 'basic_app/login.html',{})


def product_form(request):

    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'basic_app/product.html',{'form':form})

def seller_form(request):

    form = SellerForm()

    if request.method == 'POST':
        form = SellerForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'basic_app/seller.html',{'form':form})

def customer_form(request):

    form = CustomerForm()

    if request.method == 'POST':
        form = CustomerForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'basic_app/customer.html',{'form':form})

def sales_form(request):

    form = SalesForm()

    if request.method == 'POST':
        form = SalesForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'basic_app/sales.html',{'form':form})

def purchase_form(request):

    form = PurchaseForm()

    if request.method == 'POST':
        form = PurchaseForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'basic_app/purchase.html',{'form':form})

user_management/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <style>
      body {
        background-image: url("{% static 'basic_app/images/137487.jpg' %}");
      }
    </style>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Agri Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:dashboard' %}">Dashboard</a>
        </li>

        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">LogOut</a>
        </li>

        {% else %}
        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:user_login' %}">LogIn</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </div>
</nav>

<div class="container">
  {% block body_block %}
  {% endblock %}
  </div>










  </body>
</html>

user_management/templates/basic_app/customer.html
{% extends "basic_app/base.html" %}
 {% block body_block %}

 <div class="mt-4 p-10 text-white fw-bold rounded">
   <h1 class="text-white fw-bold">Add Products</h1>
   <br>
   <form  method="POST">
     {{ form.as_p }}
     {% csrf_token %}

     <br>
     <input type="submit" class="btn btn-success" name="" value="Add">
   </form>
 </div>


    {% endblock %}

user_management/templates/basic_app/dashboard.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <style>
      body {
        background-image: url("{% static 'basic_app/images/137487.jpg' %}");
      }
      a { text-decoration: none; }
    </style>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Agro Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:dashboard' %}">Dashboard</a>
        </li>

        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">LogOut</a>
        </li>

        {% else %}
        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'basic_app:user_login' %}">LogIn</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </div>
</nav>

<div class="container">


  <div class="container">
   <div class="row">
     <div class="col-sm-4">
       <br>
       <h1 class="text-white fw-bold">Dashboard</h1>
       <br>
       <br>

       <div class="p-3 mb-2 bg-primary"><a class="btn-success" href="{% url 'basic_app:product_data' %}"><h4 class="text-dark fw-bold text-center" >Product</h4></a></div>
       <div class="p-3 mb-2 bg-info "><a class="btn-success"href="{% url 'basic_app:seller_data' %}"><h4 class="text-dark fw-bold text-center" >Seller</h4></a></div>
       <div class="p-3 mb-2 bg-secondary"><a class="btn-success" href="{% url 'basic_app:customer_data' %}"><h4 class="text-dark fw-bold text-center" >Customer</h4></a></div>
       <div class="p-3 mb-2 bg-success"><a class="btn-success" href="{% url 'basic_app:sales_data' %}"><h4 class="text-dark fw-bold text-center" >Sales</h4></a></div>
       <div class="p-3 mb-2 bg-light text-dark"><a class="btn-success" href="{% url 'basic_app:purchase_data' %}"><h4 class="text-dark fw-bold text-center" >Purchase</h4></a></div>


     </div>

     <div class="col-sm-8">
       {% block body_block %}
       {% endblock %}
   </div>


  </div>










  </body>
</html>

user_management/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
 {% block body_block %}

  <div class="jumbotron">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1 class="text-white fw-bold">Welcome to Agri Management System</h1>
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'basic_app:dashboard' %}" role="button">Go to Dashboard</a>
    {% endif %}

  </div>
    {% endblock %}

user_management/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

  {% block body_block %}

  <div class="mt-4 p-10 text-white fw-bold rounded">
    <h1 class="text-white fw-bold">Please Login</h1>
    <form class="" action="{% url 'basic_app:user_login' %}" method="POST">
      {% csrf_token %}

      <br>
      <label for="username" class="form-label">UserName:</label>
      <input type="text" class="form-control" name="username" placeholder="Enter UserName">
      <br>
      <label for="password" class="form-label">Password:</label>
      <input type="password" class="form-control" name="password" placeholder="*********">

      <br>
      <input type="submit" class="btn btn-success" name="" value="Login">
    </form>
  </div>



  {% endblock %}

user_management/templates/basic_app/loginfail.html
{% extends "basic_app/base.html" %}
 {% block body_block %}
<br>

 <div class="alert alert-danger" role="alert">
  <h1>invalid login details supplied!</h1>
</div>
    {% endblock %}

user_management/templates/basic_app/product_data.html
{% extends "basic_app/dashboard.html" %}
 {% block body_block %}


    <br>
    <h1 class="text-white fw-bold">Products</h1>
    <a class="btn btn-dark" href="{% url 'basic_app:add_product' %}" role="button">Add</a>

    <div class="mt-4 p-5 bg-light  text-white rounded">
      {% if product_data %}
      <table class="table">
        <thead class="thead-dark">
          <th scope="col">Product Id</th>
          <th scope="col">Product Type</th>
          <th scope="col">Product Name</th>
          <th scope="col">Product Rate</th>
        </thead>
        {% for product in product_data %}
          <tr>
            <td>{{ product.product_id }}</td>
            <td>{{ product.product_type }}</td>
            <td>{{ product.product_name }}</td>
            <td>{{ product.product_rate }}</td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
      <p>NO ACCESS RECORDS FOUND</p>
      {% endif %}

    </div>

    {% endblock %}

user_management/templates/basic_app/purchase.html
{% extends "basic_app/base.html" %}
 {% block body_block %}

 <div class="mt-4 p-10 text-white fw-bold rounded">
   <h1 class="text-white fw-bold">Add Products</h1>
   <br>
   <form  method="POST">
     {{ form.as_p }}
     {% csrf_token %}

     <br>
     <input type="submit" class="btn btn-success" name="" value="Add">
   </form>
 </div>


    {% endblock %}

user_management/templates/basic_app/purchase_data.html
{% extends "basic_app/dashboard.html" %}
 {% block body_block %}


    <br>
    <h1 class="text-white fw-bold">Purchases</h1>
    <a class="btn btn-dark" href="{% url 'basic_app:add_purchase' %}" role="button">Add</a>

    <div class="mt-4 p-5 bg-light  text-white rounded">
      {% if purchase_data %}
      <table class="table">
        <thead class="thead-dark">
          <th scope="col">Customer Id</th>
          <th scope="col">Product Id</th>
          <th scope="col">Purchase Date</th>
          <th scope="col">purchase Qty</th>
        </thead>
        {% for purchase in purchase_data %}
          <tr>
            <td>{{ purchase.customer_id  }}</td>
            <td>{{ purchase.product_id }}</td>
            <td>{{ purchase.purchase_date }}</td>
            <td>{{ purchase.purchase_qty }}</td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
      <p>NO ACCESS RECORDS FOUND</p>
      {% endif %}

    </div>


    {% endblock %}

user_management/templates/basic_app/registraction.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

 {% block body_block %}

  <div class="mt-4 p-5 text-white fw-bold rounded">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    <button type="button" class="btn btn-warning"><a href="{% url 'basic_app:user_login' %}">Continue</a></button>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="btn btn-success" name="" value="Register">
    </form>
{% endif %}
  </div>
    {% endblock %}

user_management/templates/basic_app/sales.html
{% extends "basic_app/base.html" %}
 {% block body_block %}

 <div class="mt-4 p-10 text-white fw-bold rounded">
   <h1 class="text-white fw-bold">Add Products</h1>
   <br>
   <form  method="POST">
     {{ form.as_p }}
     {% csrf_token %}

     <br>
     <input type="submit" class="btn btn-success" name="" value="Add">
   </form>
 </div>


    {% endblock %}

user_management/templates/basic_app/sales_data.html
{% extends "basic_app/dashboard.html" %}
 {% block body_block %}


    <br>
    <h1 class="text-white fw-bold">Sales</h1>
    <a class="btn btn-dark" href="{% url 'basic_app:add_sales' %}" role="button">Add</a>

    <div class="mt-4 p-5 bg-light  text-white rounded">
      {% if sales_data %}
      <table class="table">
        <thead class="thead-dark">
          <th scope="col">Seller Id</th>
          <th scope="col">Product Id</th>
          <th scope="col">Sales Date</th>
          <th scope="col">Sales Qty</th>
        </thead>
        {% for sales in sales_data %}
          <tr>
            <td>{{ sales.seller_id  }}</td>
            <td>{{ sales.product_id }}</td>
            <td>{{ sales.sales_date }}</td>
            <td>{{ sales.sales_qty }}</td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
      <p>NO ACCESS RECORDS FOUND</p>
      {% endif %}

    </div>


    {% endblock %}

user_management/templates/basic_app/seller.html
{% extends "basic_app/base.html" %}
 {% block body_block %}

 <div class="mt-4 p-10 text-white fw-bold rounded">
   <h1 class="text-white fw-bold">Add Products</h1>
   <br>
   <form method="POST">
     {{ form.as_p }}
     {% csrf_token %}

     <br>
     <input type="submit" class="btn btn-success" name="" value="Add">
   </form>
 </div>


    {% endblock %}

user_management/templates/basic_app/seller_data.html
{% extends "basic_app/dashboard.html" %}
 {% block body_block %}


    <br>
    <h1 class="text-white fw-bold">Sellers</h1>
    <a class="btn btn-dark" href="{% url 'basic_app:add_seller' %}" role="button">Add</a>


    <div class="mt-4 p-5 bg-light  text-white rounded">
      {% if seller_data %}
      <table class="table">
        <thead class="thead-dark">
          <th scope="col">Seller Id</th>
          <th scope="col">Seller Name</th>
          <th scope="col">Seller Number</th>
          <th scope="col">Seller address</th>
        </thead>
        {% for seller in seller_data %}
          <tr>
            <td>{{ seller.seller_id }}</td>
            <td>{{ seller.seller_name }}</td>
            <td>{{ seller.seller_number }}</td>
            <td>{{ seller.seller_address }}</td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
      <p>NO ACCESS RECORDS FOUND</p>
      {% endif %}

    </div>

    {% endblock %}